name: Print comment

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "${{ github.repository }} event_name ${{ github.event_name }} actor ${{ github.actor }} repo_owner ${{ github.repository_owner }}"
      - uses: actions/checkout@v3
      - name: Print out a comment
        uses: marocchino/sticky-pull-request-comment@v2
        env:
          GITHUB_TOKEN: ${secrets.GITHUB_TOKEN}
        #if: ${{ echo github.repository || true }}
        with:
          message: Hello world ${{ github.repository }} 1 ${{ github.event_name }} 2 ${{ github.actor }} 3 ${{ github.repository_owner }}
