name: Print comment

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print out a comment
        uses: marocchino/sticky-pull-request-comment@v2
        #if: ${{ echo github.repository || true }}
        with:
          message: Hello world ${{ github.repository }}
